# Generated by Django 5.2.12 on 2026-04-05 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(default="fas fa-tools", max_length=50)),
                ("color", models.CharField(default="#007bff", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tool Category",
                "verbose_name_plural": "Tool Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("ai", "AI Response"),
                            ("system", "System Message"),
                            ("analysis_result", "Analysis Result"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="saiha.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("storage_format", models.CharField(default="parquet", max_length=20)),
                ("file_size", models.BigIntegerField()),
                ("rows_count", models.IntegerField()),
                ("columns_count", models.IntegerField()),
                ("encoding", models.CharField(default="utf-8", max_length=50)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "original_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("processed_file_path", models.CharField(max_length=500)),
                ("metadata_file_path", models.CharField(max_length=500)),
                (
                    "preview_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "parent_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_datasets",
                        to="saiha.dataset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.AddField(
            model_name="analysissession",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="saiha.dataset",
            ),
        ),
        migrations.CreateModel(
            name="DatasetColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                ("column_index", models.IntegerField()),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                        ],
                        default="string",
                        max_length=50,
                    ),
                ),
                ("null_count", models.IntegerField(default=0)),
                ("unique_count", models.IntegerField(default=0)),
                ("sample_values", models.JSONField(default=list)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="saiha.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Column",
                "verbose_name_plural": "Dataset Columns",
                "ordering": ["column_index"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("statistical", "Statistical Analysis"),
                            ("visualization", "Data Visualization"),
                            ("data_quality", "Data Quality"),
                            ("machine_learning", "Machine Learning"),
                            ("export", "Export/Import"),
                            ("other", "Other"),
                        ],
                        default="statistical",
                        max_length=50,
                    ),
                ),
                ("icon", models.CharField(default="fas fa-chart-bar", max_length=50)),
                ("color", models.CharField(default="#28a745", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_dataset", models.BooleanField(default=True)),
                (
                    "api_endpoint",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="saiha.toolcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["category__order", "order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="analysissession",
            unique_together={("user", "dataset", "is_active")},
        ),
    ]
