# Generated by Django 5.2.12 on 2026-04-05 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0002_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="analysis_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="chat_message_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="llm_cache_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool_used", models.CharField(max_length=100)),
                ("result_data", models.JSONField()),
                ("ai_interpretation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="saiha.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
