# Generated by Django 5.2.12 on 2026-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0003_analysissession_analysis_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Analysis Result",
                "verbose_name_plural": "Analysis Results",
            },
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="dedup_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="result_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
