# Generated by Django 5.2.12 on 2026-04-05 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0004_alter_analysisresult_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("model_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="saiha.analysissession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Audit Log",
                "verbose_name_plural": "AI Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
