# Generated by Django 5.2.12 on 2026-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0005_aiauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="query",
            field=models.TextField(blank=True, null=True),
        ),
    ]
