# Generated by Django 5.2.12 on 2026-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0009_aiauditlog_user_userquota"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_to_credit_rate",
                    models.IntegerField(
                        default=10000,
                        help_text="How many tokens equal 1 Credit (e.g., 10000)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Configuration",
                "verbose_name_plural": "App Configurations",
            },
        ),
    ]
