# Generated by Django 5.2.12 on 2026-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0011_corporate_corporateinvitation_corporateprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateinvitation",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="corporateinvitation",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
