# Generated by Django 5.2.12 on 2026-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0012_corporateinvitation_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateinvitation",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporateinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporateinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("ACCEPTED", "Accepted"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
