# Generated by Django 5.2.12 on 2026-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0013_corporateinvitation_last_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateprofile",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
