# Generated by Django 5.2.12 on 2026-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0014_corporateprofile_left_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfiguration",
            name="credit_cost_per_seat",
            field=models.FloatField(
                default=10.0,
                help_text="Cost in credits to purchase 1 organizational seat license.",
            ),
        ),
    ]
