# Generated by Django 5.2.12 on 2026-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0015_appconfiguration_credit_cost_per_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporate",
            name="expired_credits",
            field=models.FloatField(
                default=0,
                help_text="Unspent credits that have passed their expiry date.",
            ),
        ),
        migrations.AddField(
            model_name="corporate",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userquota",
            name="expired_tokens",
            field=models.IntegerField(
                default=0, help_text="Tokens from a previous cycle that can be rescued."
            ),
        ),
    ]
