# Generated by Django 5.2.12 on 2026-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0016_corporate_expired_credits_corporate_expiry_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Starter, Professional, Enterprise",
                        max_length=100,
                    ),
                ),
                (
                    "credits",
                    models.FloatField(
                        help_text="Amount of credits granted in this package."
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price in USD (e.g. 5.00)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this package is highlighted in the Storefront.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Credit Package",
                "verbose_name_plural": "Credit Packages",
                "ordering": ["price_usd"],
            },
        ),
    ]
