# Generated by Django 5.2.12 on 2026-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0017_creditpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditpackage",
            name="price_bdt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total price in BDT (e.g. 600.00)",
                max_digits=10,
            ),
        ),
    ]
