# Generated by Django 5.2.12 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0018_creditpackage_price_bdt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquota",
            name="expired_tokens",
            field=models.FloatField(
                default=0,
                help_text="Tokens that have expired but can be rescued upon recharge.",
            ),
        ),
    ]
