# Generated by Django 5.2.12 on 2026-04-14 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0019_alter_userquota_expired_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="Saiha AI", max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "bin_vat_number",
                    models.CharField(
                        blank=True,
                        help_text="Business Identification Number or VAT Reg.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="branding/invoices/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Info",
                "verbose_name_plural": "Business Info",
            },
        ),
        migrations.AddField(
            model_name="appconfiguration",
            name="default_vat_percentage",
            field=models.FloatField(
                default=0.0,
                help_text="Default VAT percentage to apply to invoices (e.g. 15.0)",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("subtotal_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "subtotal_local",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in BDT at time of purchase",
                        max_digits=12,
                    ),
                ),
                ("vat_percentage", models.FloatField(default=0.0)),
                (
                    "vat_amount_local",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount_local",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="BDT", max_length=10)),
                ("status", models.CharField(default="PAID", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corporate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="saiha.corporate",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="saiha.creditpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
