# Generated by Django 5.2.12 on 2026-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0020_businessinfo_appconfiguration_default_vat_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Method of payment (e.g., Credit Card, Bkash, Bank Transfer)",
                max_length=100,
                null=True,
            ),
        ),
    ]
