# Generated by Django 5.2.12 on 2026-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0023_analysissession_active_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiauditlog",
            name="tokens_cached",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="last_summary_at_message",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="llm_cache_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="llm_cache_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="memory_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="working_memory",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
