# Generated by Django 5.2.12 on 2026-04-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0024_aiauditlog_tokens_cached_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiauditlog",
            name="cache_hit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aiauditlog",
            name="summary_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiauditlog",
            name="working_memory_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="analysis_chain",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
