# Generated by Django 5.2.12 on 2026-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0025_aiauditlog_cache_hit_aiauditlog_summary_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="last_valid_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
