# Generated by Django 5.2.12 on 2026-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saiha", "0026_analysissession_last_valid_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiauditlog",
            name="metadata_status",
            field=models.CharField(default="none", max_length=20),
        ),
    ]
